In [1]:
import os
import pandas as pd

In [10]:
dfs = []
for f in sorted(os.listdir()):
    if f.endswith('xlsx'): 
        print(f)
        dfs += [pd.read_excel(f,index_col=None)]
len(dfs)

国有股持股数.xlsx
民营上市公司数据.xlsx
研发投入占比.xlsx
资产负债和利润.xlsx

4

In [11]:
print(dfs[0].shape)
dfs[0].head()

(32173, 6)

    Stkcd      Reptdt      Nshrttl  Nshrstt    Nshremp    Nshrsms
0   证券代码'     统计截止日期'        股本总数'  其中：国有股'  其中：内部职工股'  其中：高管持股数'
1   没有单位'       没有单位'           股'       股'         股'         股'
2  000001  2017-12-31  17170411366        0          0      23866
3  000001  2016-12-31  17170411366        0          0      17587
4  000001  2015-12-31  14308676139        0          0      14657

In [12]:
print(dfs[1].shape)
dfs[1].head()

(17145, 38)

,Stkcd,Reptdt,Stknme,Listexg,Conme,Nindcd,Nindnme,Regadd,Area,Province,...,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap
0,证券代码',统计截止日期',证券简称',上市交易所',公司中文全称',行业代码',行业名称',公司注册地址',地区',省份',...,总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图'
1,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',...,没有单位',元',元',元',元',元',元',没有单位',没有单位',没有单位'
2,000004,2003-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,0.0519,440000,900000,9.94558e+07,2.37875e+08,1.19535e+08,7.64138e+06,0.0595,北京大学为北京北大未名生物工程集团的控股股东。,NaN
3,000004,2004-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,0.0519,450000,930000,8.11425e+07,2.1427e+08,1.06748e+08,-3.28293e+06,-0.0268,北京大学为北京北大未名生物工程集团的控股股东。,NaN
4,000004,2005-12-31,国农科技,2,深圳中国农大科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,0,440000,660000,5.51325e+07,1.55869e+08,6.13767e+07,-1.85774e+07,-0.1859,NaN,NaN

In [13]:
print(dfs[2].shape)
dfs[2].head()

(15850, 7)

,Symbol,EndDate,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation
0,证券代码',统计截止日期',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明'
1,没有单位',没有单位',人',没有单位',没有单位',没有单位',没有单位'
2,000004,2017-12-31,23,13.77,5.15397e+06,3.72,"本期研发费用中,内部研发费用3,153,966.37元,外部研发费用2,000,000元,全..."
3,000004,2016-12-31,NaN,NaN,9.2444e+06,NaN,NaN
4,000005,2016-12-31,NaN,NaN,1.68114e+07,NaN,NaN

In [14]:
print(dfs[3].shape)
dfs[3].head()

(39037, 11)

,Symbol,EndDate,IndustryCode,IndustryName,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',年度区间',行业代码',行业名称',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,没有单位',没有单位',没有单位',没有单位',元',元',元',元',元',元',元'
2,000001,2017-12-31,J66,货币金融服务,3248474000000,3026420000000,4701000000,23189000000,NaN,NaN,30223000000
3,000001,2016-12-31,J66,货币金融服务,2953434000000,2751263000000,4771000000,22599000000,NaN,NaN,29779000000
4,000001,2015-12-31,J66,货币金融服务,2507149000000,2345649000000,4961000000,21865000000,NaN,NaN,28895000000

In [16]:
dfs[2] = dfs[2].rename(columns={'Symbol':'Stkcd','EndDate':'Reptdt'})
dfs[2].head()

,Stkcd,Reptdt,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation
0,证券代码',统计截止日期',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明'
1,没有单位',没有单位',人',没有单位',没有单位',没有单位',没有单位'
2,000004,2017-12-31,23,13.77,5.15397e+06,3.72,"本期研发费用中,内部研发费用3,153,966.37元,外部研发费用2,000,000元,全..."
3,000004,2016-12-31,NaN,NaN,9.2444e+06,NaN,NaN
4,000005,2016-12-31,NaN,NaN,1.68114e+07,NaN,NaN

In [17]:
dfs[3] = dfs[3].rename(columns={'Symbol':'Stkcd','EndDate':'Reptdt'})
dfs[3].head()

,Stkcd,Reptdt,IndustryCode,IndustryName,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',年度区间',行业代码',行业名称',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,没有单位',没有单位',没有单位',没有单位',元',元',元',元',元',元',元'
2,000001,2017-12-31,J66,货币金融服务,3248474000000,3026420000000,4701000000,23189000000,NaN,NaN,30223000000
3,000001,2016-12-31,J66,货币金融服务,2953434000000,2751263000000,4771000000,22599000000,NaN,NaN,29779000000
4,000001,2015-12-31,J66,货币金融服务,2507149000000,2345649000000,4961000000,21865000000,NaN,NaN,28895000000

In [13]:
max_row, total_column=max([v.shape[0] for v in dfs]),sum([v.shape[1] for v in dfs])
max_row,total_column

(39037, 62)

In [53]:
# 民营上市公司数据 
# 国有股持股数 
# 研发投入占比.xlsx
# 资产负债和利润.xlsx
df = dfs[1].merge(dfs[0],how='outer').merge(dfs[2],how='outer').merge(dfs[3],how='outer')
print(df.shape)
df = df.dropna(subset=['Conme']) #过滤证券简称和中文名为空的
print(df.shape)
df.head()

(39609, 52)
(17184, 52)

,Stkcd,Reptdt,Stknme,Listexg,Conme,Nindcd,Nindnme,Regadd,Area,Province,...,Explanation,IndustryCode,IndustryName,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',证券简称',上市交易所',公司中文全称',行业代码',行业名称',公司注册地址',地区',省份',...,说明',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',...,没有单位',没有单位',没有单位',元',元',元',元',元',元',元'
2,000004,2003-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,NaN,G54,道路运输业,2.37875e+08,1.09456e+08,1.48256e+06,7.64138e+06,1.19535e+08,6.82115e+07,4.71244e+06
3,000004,2004-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,NaN,G54,道路运输业,2.1427e+08,9.16425e+07,3.14682e+06,-3.28293e+06,1.06748e+08,69169581,-7.51987e+06
4,000004,2005-12-31,国农科技,2,深圳中国农大科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,NaN,G54,道路运输业,1.55869e+08,5.59325e+07,2.86283e+06,-1.85774e+07,6.13767e+07,3.70423e+07,-2.18882e+07

In [19]:
# import datetime
# date = datetime.datetime.now().strftime('%Y%m%d')
# df.to_excel('out_join_'+date+'.xlsx')

In [54]:

x = df.to_dict('records')
x[0:5]

[{'A001000000': "总资产'",
  'A002100000': "流动负债'",
  'Area': "地区'",
  'B001100000': "营业收入'",
  'B002000000': "净利润'",
  'Bdnum': "董事会人数'",
  'Chmap': "控制链图'",
  'City': "城市'",
  'Conme': "公司中文全称'",
  'Dbdbum': "其中：独董人数'",
  'Empnum': "员工人数'",
  'Explanation': "说明'",
  'Hdirrt': "总经理持股比例(%)'",
  'IndustryCode': nan,
  'IndustryName': nan,
  'IntangibleAsset': nan,
  'Listdt': "上市日期'",
  'Listexg': "上市交易所'",
  'Mtnum': "监事会人数'",
  'NetProfit': nan,
  'Nindcd': "行业代码'",
  'Nindnme': "行业名称'",
  'Nshld': "股东总数'",
  'OperatingCost': nan,
  'OperatingEvenue': nan,
  'OperationProfit': nan,
  'Preshrt': "董事长持股比例(%)'",
  'Prestw3': "董事前三名薪酬总额'",
  'Pridt': "转化日期'",
  'Primed': "民营化方式'",
  'Prisg': "民营化标志'",
  'Province': "省份'",
  'RDPerson': "研发人员数量'",
  'RDPersonRatio': "研发人员数量占比(%)'",
  'RDSpendSum': "研发投入金额'",
  'RDSpendSumRatio': "研发投入占营业收入比例(%)'",
  'Regadd': "公司注册地址'",
  'Reptdt': "统计截止日期'",
  'Retnum': "离退休职工人数'",
  'Stkcd': "证券代码'",
  'Stknme': "证券简称'",
  'T40801': "净资产收益率(%)'",
  'TotalAssets': nan,
  'TotalLiability': nan,
  'Ucpd': "实际控制人是否担任董事长或总经理'",
  'Ucsbg': "实际控制人背景'",
  'Ucscm': "实际控制人控制上市公司方式'",
  'Ucscr': "实际控制人拥有上市公司所有权比例(%)'",
  'Ucsnm': "实际控制人名称'",
  'Ucsp': "实际控制人类型'",
  'Ucsvr': "实际控制人拥有上市公司控制权比例(%)'",
  'Vmntw3': "高管前三名薪酬总额'"},
 {'A001000000': "元'",
  'A002100000': "元'",
  'Area': "没有单位'",
  'B001100000': "元'",
  'B002000000': "元'",
  'Bdnum': "人'",
  'Chmap': "没有单位'",
  'City': "没有单位'",
  'Conme': "没有单位'",
  'Dbdbum': "人'",
  'Empnum': "人'",
  'Explanation': "没有单位'",
  'Hdirrt': "没有单位'",
  'IndustryCode': "没有单位'",
  'IndustryName': "没有单位'",
  'IntangibleAsset': "元'",
  'Listdt': "没有单位'",
  'Listexg': "没有单位'",
  'Mtnum': "人'",
  'NetProfit': "元'",
  'Nindcd': "没有单位'",
  'Nindnme': "没有单位'",
  'Nshld': "人'",
  'OperatingCost': "元'",
  'OperatingEvenue': "元'",
  'OperationProfit': "元'",
  'Preshrt': "没有单位'",
  'Prestw3': "元'",
  'Pridt': "没有单位'",
  'Primed': "没有单位'",
  'Prisg': "没有单位'",
  'Province': "没有单位'",
  'RDPerson': "人'",
  'RDPersonRatio': "没有单位'",
  'RDSpendSum': "没有单位'",
  'RDSpendSumRatio': "没有单位'",
  'Regadd': "没有单位'",
  'Reptdt': "没有单位'",
  'Retnum': "人'",
  'Stkcd': "没有单位'",
  'Stknme': "没有单位'",
  'T40801': "没有单位'",
  'TotalAssets': "元'",
  'TotalLiability': "元'",
  'Ucpd': "没有单位'",
  'Ucsbg': "没有单位'",
  'Ucscm': "没有单位'",
  'Ucscr': "没有单位'",
  'Ucsnm': "没有单位'",
  'Ucsp': "没有单位'",
  'Ucsvr': "没有单位'",
  'Vmntw3': "元'"},
 {'A001000000': 237875156.04,
  'A002100000': 99455758.58,
  'Area': '华南',
  'B001100000': 119534953.77,
  'B002000000': 7641381.76,
  'Bdnum': 9,
  'Chmap': nan,
  'City': '深圳市',
  'Conme': '深圳市北大高科技股份有限公司',
  'Dbdbum': 3,
  'Empnum': 344,
  'Explanation': nan,
  'Hdirrt': 0.0519,
  'IndustryCode': 'G54',
  'IndustryName': '道路运输业',
  'IntangibleAsset': 1482563.54,
  'Listdt': '1991-01-14',
  'Listexg': '2',
  'Mtnum': 3,
  'NetProfit': 7641381.76,
  'Nindcd': 'G54',
  'Nindnme': '道路运输业',
  'Nshld': 14518,
  'OperatingCost': 68211544.36,
  'OperatingEvenue': 119534953.77,
  'OperationProfit': 4712436.83,
  'Preshrt': 0,
  'Prestw3': 440000,
  'Pridt': nan,
  'Primed': nan,
  'Prisg': '0',
  'Province': '广东省',
  'RDPerson': nan,
  'RDPersonRatio': nan,
  'RDSpendSum': nan,
  'RDSpendSumRatio': nan,
  'Regadd': '深圳市蛇口新时代广场27楼A-D',
  'Reptdt': '2003-12-31',
  'Retnum': 1,
  'Stkcd': '000004',
  'Stknme': '北大高科',
  'T40801': 0.0595,
  'TotalAssets': 237875156.04,
  'TotalLiability': 109455758.58,
  'Ucpd': '0',
  'Ucsbg': '北京大学为北京北大未名生物工程集团的控股股东。',
  'Ucscm': '2',
  'Ucscr': 9.1056,
  'Ucsnm': '北京大学',
  'Ucsp': '1',
  'Ucsvr': 37.94,
  'Vmntw3': 900000},
 {'A001000000': 214270248.77,
  'A002100000': 81142530.91,
  'Area': '华南',
  'B001100000': 106747751.86,
  'B002000000': -3282932.11,
  'Bdnum': 9,
  'Chmap': nan,
  'City': '深圳市',
  'Conme': '深圳市北大高科技股份有限公司',
  'Dbdbum': 3,
  'Empnum': 303,
  'Explanation': nan,
  'Hdirrt': 0.0519,
  'IndustryCode': 'G54',
  'IndustryName': '道路运输业',
  'IntangibleAsset': 3146817.72,
  'Listdt': '1991-01-14',
  'Listexg': '2',
  'Mtnum': 3,
  'NetProfit': -3282932.11,
  'Nindcd': 'G54',
  'Nindnme': '道路运输业',
  'Nshld': 17032,
  'OperatingCost': 69169581,
  'OperatingEvenue': 106747751.86,
  'OperationProfit': -7519874.6,
  'Preshrt': 0,
  'Prestw3': 450000,
  'Pridt': nan,
  'Primed': nan,
  'Prisg': '0',
  'Province': '广东省',
  'RDPerson': nan,
  'RDPersonRatio': nan,
  'RDSpendSum': nan,
  'RDSpendSumRatio': nan,
  'Regadd': '深圳市蛇口新时代广场27楼A-D',
  'Reptdt': '2004-12-31',
  'Retnum': 0,
  'Stkcd': '000004',
  'Stknme': '北大高科',
  'T40801': -0.0268,
  'TotalAssets': 214270248.77,
  'TotalLiability': 91642530.91,
  'Ucpd': '0',
  'Ucsbg': '北京大学为北京北大未名生物工程集团的控股股东。',
  'Ucscm': '2',
  'Ucscr': 9.1056,
  'Ucsnm': '北京大学',
  'Ucsp': '1',
  'Ucsvr': 37.94,
  'Vmntw3': 930000},
 {'A001000000': 155868770.91,
  'A002100000': 55132540.19,
  'Area': '华南',
  'B001100000': 61376724.83,
  'B002000000': -18577413.51,
  'Bdnum': 9,
  'Chmap': nan,
  'City': '深圳市',
  'Conme': '深圳中国农大科技股份有限公司',
  'Dbdbum': 3,
  'Empnum': 284,
  'Explanation': nan,
  'Hdirrt': 0,
  'IndustryCode': 'G54',
  'IndustryName': '道路运输业',
  'IntangibleAsset': 2862825.77,
  'Listdt': '1991-01-14',
  'Listexg': '2',
  'Mtnum': 3,
  'NetProfit': -18577413.51,
  'Nindcd': 'G54',
  'Nindnme': '道路运输业',
  'Nshld': 16366,
  'OperatingCost': 37042271.75,
  'OperatingEvenue': 61376724.83,
  'OperationProfit': -21888181.45,
  'Preshrt': 0,
  'Prestw3': 440000,
  'Pridt': nan,
  'Primed': nan,
  'Prisg': '0',
  'Province': '广东省',
  'RDPerson': nan,
  'RDPersonRatio': nan,
  'RDSpendSum': nan,
  'RDSpendSumRatio': nan,
  'Regadd': '深圳市蛇口新时代广场27楼A-D',
  'Reptdt': '2005-12-31',
  'Retnum': 0,
  'Stkcd': '000004',
  'Stknme': '国农科技',
  'T40801': -0.1859,
  'TotalAssets': 155868770.91,
  'TotalLiability': 55932540.19,
  'Ucpd': '0',
  'Ucsbg': nan,
  'Ucscm': '2',
  'Ucscr': 22.4385,
  'Ucsnm': '中国农业大学',
  'Ucsp': '1',
  'Ucsvr': 37.94,
  'Vmntw3': 660000}]

In [55]:
# 过滤 没有包含2015 2016 2017 这三年数据的公司
idMap = {}
for a in df.to_dict('records'):
    id = a['Stkcd']
    year = a['Reptdt']
    if not a['Stknme']:
        continue
    if '2018' in year:
        continue

    if id not in idMap:
        idMap[id] = [];
    idMap[id].append(year[0:4])

reversedId = []
expected = set(['2015','2016','2017'])
for (k,v) in  idMap.items(): 
    if set(v) & expected:
        reversedId.append(k)
    
print(len(reversedId),len(idMap.keys())) 
df2 = df[df["Stkcd"].isin(reversedId)]  
print(df.shape)
print(df2.shape)
# 还剩下 3513记录

1786 1817
(17184, 52)
(17049, 52)

In [67]:
# 过滤 名称中包含ST的
import functools 
idMap = {}
for a in df.to_dict('records'):
    id = a['Stkcd']
    if id not in idMap:
        idMap[id] = [];
    idMap[id].append(a['Stknme'])
reversedId = []
for (k,v) in  idMap.items(): 
    stNum = functools.reduce(lambda x,y: (1+x) if 'ST' in y  else  (0 + x) , v, 0)
    if stNum <10:
        reversedId.append(k)
        

df3 = df2[df2["Stkcd"].isin(reversedId)]  
print(df2.shape)
print(df3.shape)
print(df2.shape[0]-df3.shape[0])

(17049, 52)
(16779, 52)
270

In [68]:


df3.to_excel('out_join2_'+date+'.xlsx')