In [ ]:
"""
1.把下面四个文件合并为一个文件：
    国有股持股数.xlsx
    民营上市公司数据.xlsx
    研发投入占比.xlsx
    资产负债和利润.xlsx
    
2.过滤近三年缺失的记录
3.过滤10年ST的公司
"""

In [107]:
import os
import pandas as pd
pd.set_option('display.max_columns', 500)

In [96]:
base_dir = './'
from IPython.display import display
def load(f):
    df_ = pd.read_excel(f,index_col=None)
    print(f,df_.shape)
    display(df_.head(3))
    return df_
df1_ = load('国有股持股数.xlsx')

国有股持股数.xlsx (32173, 6)

    Stkcd      Reptdt      Nshrttl  Nshrstt    Nshremp    Nshrsms
0   证券代码'     统计截止日期'        股本总数'  其中：国有股'  其中：内部职工股'  其中：高管持股数'
1   没有单位'       没有单位'           股'       股'         股'         股'
2  000001  2017-12-31  17170411366        0          0      23866

In [97]:
df2_ = load('民营上市公司数据.xlsx')

民营上市公司数据.xlsx (17145, 38)

,Stkcd,Reptdt,Stknme,Listexg,Conme,Nindcd,Nindnme,Regadd,Area,Province,...,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap
0,证券代码',统计截止日期',证券简称',上市交易所',公司中文全称',行业代码',行业名称',公司注册地址',地区',省份',...,总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图'
1,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',...,没有单位',元',元',元',元',元',元',没有单位',没有单位',没有单位'
2,000004,2003-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,0.0519,440000,900000,9.94558e+07,2.37875e+08,1.19535e+08,7.64138e+06,0.0595,北京大学为北京北大未名生物工程集团的控股股东。,NaN

In [98]:
df3_ = load('研发投入占比.xlsx')

研发投入占比.xlsx (15850, 7)

,Symbol,EndDate,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation
0,证券代码',统计截止日期',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明'
1,没有单位',没有单位',人',没有单位',没有单位',没有单位',没有单位'
2,000004,2017-12-31,23,13.77,5.15397e+06,3.72,"本期研发费用中,内部研发费用3,153,966.37元,外部研发费用2,000,000元,全..."

In [99]:
df4_ = load('资产负债和利润.xlsx')

资产负债和利润.xlsx (39037, 11)

,Symbol,EndDate,IndustryCode,IndustryName,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',年度区间',行业代码',行业名称',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,没有单位',没有单位',没有单位',没有单位',元',元',元',元',元',元',元'
2,000001,2017-12-31,J66,货币金融服务,3248474000000,3026420000000,4701000000,23189000000,NaN,NaN,30223000000

In [100]:
df1 = df1_.rename(columns={'Stkcd':'Symbol','Reptdt':'EndDate'})
df1 = df1.drop([1])
df1.head(3)

   Symbol     EndDate      Nshrttl  Nshrstt    Nshremp    Nshrsms
0   证券代码'     统计截止日期'        股本总数'  其中：国有股'  其中：内部职工股'  其中：高管持股数'
2  000001  2017-12-31  17170411366        0          0      23866
3  000001  2016-12-31  17170411366        0          0      17587

In [101]:
df2 = df2_.rename(columns={'Stkcd':'Symbol','Reptdt':'EndDate'})
df2 = df2.drop([1])
df2.head(3)
# df4.loc[0,'EndDate']="统计截止日期'"

,Symbol,EndDate,Stknme,Listexg,Conme,Nindcd,Nindnme,Regadd,Area,Province,...,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap
0,证券代码',统计截止日期',证券简称',上市交易所',公司中文全称',行业代码',行业名称',公司注册地址',地区',省份',...,总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图'
2,000004,2003-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,0.0519,440000,900000,9.94558e+07,2.37875e+08,1.19535e+08,7.64138e+06,0.0595,北京大学为北京北大未名生物工程集团的控股股东。,NaN
3,000004,2004-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,...,0.0519,450000,930000,8.11425e+07,2.1427e+08,1.06748e+08,-3.28293e+06,-0.0268,北京大学为北京北大未名生物工程集团的控股股东。,NaN

In [102]:
df3 = df3_.drop([1])
df3.head(3)

,Symbol,EndDate,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation
0,证券代码',统计截止日期',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明'
2,000004,2017-12-31,23,13.77,5.15397e+06,3.72,"本期研发费用中,内部研发费用3,153,966.37元,外部研发费用2,000,000元,全..."
3,000004,2016-12-31,NaN,NaN,9.2444e+06,NaN,NaN

In [103]:
df4 = df4_.drop([1])
df4.loc[0,'EndDate']="统计截止日期'"
df4.head(3)

,Symbol,EndDate,IndustryCode,IndustryName,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',行业代码',行业名称',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
2,000001,2017-12-31,J66,货币金融服务,3248474000000,3026420000000,4701000000,23189000000,NaN,NaN,30223000000
3,000001,2016-12-31,J66,货币金融服务,2953434000000,2751263000000,4771000000,22599000000,NaN,NaN,29779000000

In [104]:
dfs=[df1,df2,df3,df4]
max_row, total_column=max([v.shape[0] for v in dfs]),sum([v.shape[1] for v in dfs])
print(f'max_row={max_row},total_column={total_column}')

max_row=39036,total_column=62

In [113]:
"""
    国有股持股数.xlsx
    民营上市公司数据.xlsx
    研发投入占比.xlsx
    资产负债和利润.xlsx
"""
df = dfs[1].merge(dfs[0],how='outer',on=['Symbol','EndDate']).merge(dfs[2],how='outer',on=['Symbol','EndDate']).merge(dfs[3],how='outer',on=['Symbol','EndDate'])
print(df.shape)
df.head(3)

(39657, 56)

,Symbol,EndDate,Stknme,Listexg,Conme,Nindcd,Nindnme,Regadd,Area,Province,City,Listdt,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,IndustryCode,IndustryName,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',证券简称',上市交易所',公司中文全称',行业代码',行业名称',公司注册地址',地区',省份',城市',上市日期',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',行业代码',行业名称',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,000004,2003-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,深圳市,1991-01-14,NaN,0,NaN,北京大学,1,2,0,37.94,9.1056,14518,344,1,9,3,3,0,0.0519,440000,900000,9.94558e+07,2.37875e+08,1.19535e+08,7.64138e+06,0.0595,北京大学为北京北大未名生物工程集团的控股股东。,NaN,83976684,31863151,0,236,NaN,NaN,NaN,NaN,NaN,G54,道路运输业,2.37875e+08,1.09456e+08,1.48256e+06,7.64138e+06,1.19535e+08,6.82115e+07,4.71244e+06
2,000004,2004-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,深圳市,1991-01-14,NaN,0,NaN,北京大学,1,2,0,37.94,9.1056,17032,303,0,9,3,3,0,0.0519,450000,930000,8.11425e+07,2.1427e+08,1.06748e+08,-3.28293e+06,-0.0268,北京大学为北京北大未名生物工程集团的控股股东。,NaN,83976684,31863151,0,236,NaN,NaN,NaN,NaN,NaN,G54,道路运输业,2.1427e+08,9.16425e+07,3.14682e+06,-3.28293e+06,1.06748e+08,69169581,-7.51987e+06

In [106]:
"""
下面为合并基础信息表
"""
df5_ = load('上市公司基本信息年度表2000-2017.xlsx')

上市公司基本信息年度表2000-2017.xlsx (35624, 27)

,ListedCoID,SecurityID,Symbol,ShortName,EndDate,IndustryName,IndustryCode,RegisterAddress,OfficeAddress,Zipcode,...,Lng,Lat,ISIN,FullName,LegalRepresentative,EstablishDate,Crcd,RegisterCapital,Website,BusinessScope
0,上市公司ID',证券ID',股票代码',股票简称',年度区间',行业名称',行业代码',注册具体地址',公司办公地址',办公地址邮政编码',...,经度',纬度',ISIN编码',中文全称',法人代表',公司成立日期',ABH股交叉码',注册资本',公司网址',经营范围'
1,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',...,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位'
2,101704,201000000001,000001,平安银行,2017-12-31,货币金融服务,J66,广东省深圳市罗湖区深南东路5047号,广东省深圳市深南东路5047号,518001,...,22.5407,114.108,CNE000000040,平安银行股份有限公司,谢永林,1987-12-22 00:00:00.,NaN,740180802,www.bank.pingan.com,叉车、装载机、工程机械、矿山起重运输机械及配件、铸锻件、热处理件制造及产品销售。金属材料、化...

In [114]:
"""
1.删除无意义的第二行
2.对第一行的中文字段名称规范化
3.过滤有意义的字段
4.对EstablishDate 公司成立日期' 只保留年份
"""
df5=df5_.drop([1])
df5.loc[0,'EndDate']="统计截止日期'"
df5.loc[0,'Symbol']="证券代码'"
# 过滤对
df5=df5[['Symbol','EndDate','ShortName','IndustryName','IndustryCode','RegisterAddress','Zipcode','EstablishDate']]
df5.loc[:,"EstablishDate"] =[ i[:4] if type(i) is str and len(i)>9 else i for i in df5["EstablishDate"]]
df5.head(3)

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate
0,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期'
2,000001,2017-12-31,平安银行,货币金融服务,J66,广东省深圳市罗湖区深南东路5047号,518001,1987
3,000001,2016-12-31,平安银行,货币金融服务,J66,广东省深圳市罗湖区深南东路5047号,518001,1987

In [115]:
df =df.merge(df5,how='left',on=['Symbol','EndDate'],suffixes=('_x', ''))
print('atfter merge 基本信息年度表,shape=',df.shape)
df.head(3)

atfter merge 基本信息年度表,shape= (39657, 62)

,Symbol,EndDate,Stknme,Listexg,Conme,Nindcd,Nindnme,Regadd,Area,Province,City,Listdt,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,IndustryCode_x,IndustryName_x,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate
0,证券代码',统计截止日期',证券简称',上市交易所',公司中文全称',行业代码',行业名称',公司注册地址',地区',省份',城市',上市日期',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',行业代码',行业名称',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期'
1,000004,2003-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,深圳市,1991-01-14,NaN,0,NaN,北京大学,1,2,0,37.94,9.1056,14518,344,1,9,3,3,0,0.0519,440000,900000,9.94558e+07,2.37875e+08,1.19535e+08,7.64138e+06,0.0595,北京大学为北京北大未名生物工程集团的控股股东。,NaN,83976684,31863151,0,236,NaN,NaN,NaN,NaN,NaN,G54,道路运输业,2.37875e+08,1.09456e+08,1.48256e+06,7.64138e+06,1.19535e+08,6.82115e+07,4.71244e+06,北大高科,医药制造业,C27,深圳市蛇口新时代广场27楼A-D,518057,1986
2,000004,2004-12-31,北大高科,2,深圳市北大高科技股份有限公司,G54,道路运输业,深圳市蛇口新时代广场27楼A-D,华南,广东省,深圳市,1991-01-14,NaN,0,NaN,北京大学,1,2,0,37.94,9.1056,17032,303,0,9,3,3,0,0.0519,450000,930000,8.11425e+07,2.1427e+08,1.06748e+08,-3.28293e+06,-0.0268,北京大学为北京北大未名生物工程集团的控股股东。,NaN,83976684,31863151,0,236,NaN,NaN,NaN,NaN,NaN,G54,道路运输业,2.1427e+08,9.16425e+07,3.14682e+06,-3.28293e+06,1.06748e+08,69169581,-7.51987e+06,北大高科,医药制造业,C27,深圳市蛇口新时代广场27楼A-D,518057,1986

In [116]:
"""
对多余的内容重复字段进行过滤
"""
list1 = df.columns.tolist()
list2= ['Stknme','Nindcd','Area','Listdt']
clist = [i for i in list1 if i not in list2] 
# 把基础信息的字段放在前面，方便查看
last_columns = df5.columns.tolist()
for i in clist:
    if i.endswith('_x'):
        continue
    if i not in last_columns:
        last_columns.append(i)
print(last_columns,f'new len={len(last_columns)},df5={len(df5.columns.tolist())},df={len(df.columns.tolist())}')
df = df[last_columns]
df.head(3)

['Symbol', 'EndDate', 'ShortName', 'IndustryName', 'IndustryCode', 'RegisterAddress', 'Zipcode', 'EstablishDate', 'Listexg', 'Conme', 'Nindnme', 'Regadd', 'Province', 'City', 'Primed', 'Prisg', 'Pridt', 'Ucsnm', 'Ucsp', 'Ucscm', 'Ucpd', 'Ucsvr', 'Ucscr', 'Nshld', 'Empnum', 'Retnum', 'Bdnum', 'Dbdbum', 'Mtnum', 'Preshrt', 'Hdirrt', 'Prestw3', 'Vmntw3', 'A002100000', 'A001000000', 'B001100000', 'B002000000', 'T40801', 'Ucsbg', 'Chmap', 'Nshrttl', 'Nshrstt', 'Nshremp', 'Nshrsms', 'RDPerson', 'RDPersonRatio', 'RDSpendSum', 'RDSpendSumRatio', 'Explanation', 'TotalAssets', 'TotalLiability', 'IntangibleAsset', 'NetProfit', 'OperatingEvenue', 'OperatingCost', 'OperationProfit'] new len=56,df5=8,df=62

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期',上市交易所',公司中文全称',行业名称',公司注册地址',省份',城市',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,000004,2003-12-31,北大高科,医药制造业,C27,深圳市蛇口新时代广场27楼A-D,518057,1986,2,深圳市北大高科技股份有限公司,道路运输业,深圳市蛇口新时代广场27楼A-D,广东省,深圳市,NaN,0,NaN,北京大学,1,2,0,37.94,9.1056,14518,344,1,9,3,3,0,0.0519,440000,900000,9.94558e+07,2.37875e+08,1.19535e+08,7.64138e+06,0.0595,北京大学为北京北大未名生物工程集团的控股股东。,NaN,83976684,31863151,0,236,NaN,NaN,NaN,NaN,NaN,2.37875e+08,1.09456e+08,1.48256e+06,7.64138e+06,1.19535e+08,6.82115e+07,4.71244e+06
2,000004,2004-12-31,北大高科,医药制造业,C27,深圳市蛇口新时代广场27楼A-D,518057,1986,2,深圳市北大高科技股份有限公司,道路运输业,深圳市蛇口新时代广场27楼A-D,广东省,深圳市,NaN,0,NaN,北京大学,1,2,0,37.94,9.1056,17032,303,0,9,3,3,0,0.0519,450000,930000,8.11425e+07,2.1427e+08,1.06748e+08,-3.28293e+06,-0.0268,北京大学为北京北大未名生物工程集团的控股股东。,NaN,83976684,31863151,0,236,NaN,NaN,NaN,NaN,NaN,2.1427e+08,9.16425e+07,3.14682e+06,-3.28293e+06,1.06748e+08,69169581,-7.51987e+06

In [149]:
# 民营上市公司数据 
# 国有股持股数 
# 研发投入占比.xlsx
# 资产负债和利润.xlsx
df= dfbak
dfbak = df
df = df.sort_values(by=['Symbol', 'EndDate'])
print('总公司数',df.shape,len(set(df["Symbol"])),len(df["EndDate"]))  
# 只保留 2003~2017 这15的数据
import re
re_regex = re.compile('^\d{4}')
def checkYear(x):
#     print(x)
    endDate = x['EndDate']
    if re_regex.search(endDate):
        year = int(endDate[:4])
        if 2003<= year <= 2017:
            return True
    else:
        return True
    return False

df = df[df.apply(checkYear,axis=1)]
print('过滤2018年数据后，总公司数',len(set(df["Symbol"])),len(df["Symbol"]))    
# df = df.dropna(subset=['Conme']) #过滤证券简称和中文名为空的
print(df.shape)
df.head(3)

总公司数 (32194, 56) 3598 32194
过滤2018年数据后，总公司数 3598 32194
(32194, 56)

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
17197,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250
17196,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585
17195,000001,2005-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,229216415808,224173373853,41580457,351727460,NaN,NaN,674754526

In [171]:
# 把最后一行移到第一行
dfx = df.reset_index(drop=True)
print('input table(after reset_index)')
display(dfx.head())
dfxx= dfx.reindex([len(dfx)-1]+list(range(len(dfx)-1)))
print('output table(after reindex)')
display(dfxx.head(3))
dfxx = dfxx.reset_index(drop=True)
print('output table(after reset_index)')
display(dfxx.head(3))

input table(after reset_index)

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250
1,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585
2,000001,2005-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,229216415808,224173373853,41580457,351727460,NaN,NaN,674754526
3,000001,2006-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,260576263238,254101799991,26567410,1302906538,NaN,NaN,1905168852
4,000001,2007-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2293407145,4626234,0,14838,NaN,NaN,NaN,NaN,NaN,352539361000,339533298000,67725000,2649903000,NaN,NaN,3721942000

output table(after reindex)

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
32193,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期',上市交易所',公司中文全称',行业名称',公司注册地址',省份',城市',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
0,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250
1,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585

output table(after reset_index)

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期',上市交易所',公司中文全称',行业名称',公司注册地址',省份',城市',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250
2,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585

In [173]:
df = dfxx
x = dfxx.to_dict('records')
x[0]

{'Symbol': "证券代码'",
 'EndDate': "统计截止日期'",
 'ShortName': "股票简称'",
 'IndustryName': "行业名称'",
 'IndustryCode': "行业代码'",
 'RegisterAddress': "注册具体地址'",
 'Zipcode': "办公地址邮政编码'",
 'EstablishDate': "公司成立日期'",
 'Listexg': "上市交易所'",
 'Conme': "公司中文全称'",
 'Nindnme': "行业名称'",
 'Regadd': "公司注册地址'",
 'Province': "省份'",
 'City': "城市'",
 'Primed': "民营化方式'",
 'Prisg': "民营化标志'",
 'Pridt': "转化日期'",
 'Ucsnm': "实际控制人名称'",
 'Ucsp': "实际控制人类型'",
 'Ucscm': "实际控制人控制上市公司方式'",
 'Ucpd': "实际控制人是否担任董事长或总经理'",
 'Ucsvr': "实际控制人拥有上市公司控制权比例(%)'",
 'Ucscr': "实际控制人拥有上市公司所有权比例(%)'",
 'Nshld': "股东总数'",
 'Empnum': "员工人数'",
 'Retnum': "离退休职工人数'",
 'Bdnum': "董事会人数'",
 'Dbdbum': "其中：独董人数'",
 'Mtnum': "监事会人数'",
 'Preshrt': "董事长持股比例(%)'",
 'Hdirrt': "总经理持股比例(%)'",
 'Prestw3': "董事前三名薪酬总额'",
 'Vmntw3': "高管前三名薪酬总额'",
 'A002100000': "流动负债'",
 'A001000000': "总资产'",
 'B001100000': "营业收入'",
 'B002000000': "净利润'",
 'T40801': "净资产收益率(%)'",
 'Ucsbg': "实际控制人背景'",
 'Chmap': "控制链图'",
 'Nshrttl': "股本总数'",
 'Nshrstt': "其中：国有股'",
 'Nshremp': "其中：内部职工股'",
 'Nshrsms': "其中：高管持股数'",
 'RDPerson': "研发人员数量'",
 'RDPersonRatio': "研发人员数量占比(%)'",
 'RDSpendSum': "研发投入金额'",
 'RDSpendSumRatio': "研发投入占营业收入比例(%)'",
 'Explanation': "说明'",
 'TotalAssets': "总资产'",
 'TotalLiability': "总负债'",
 'IntangibleAsset': "无形资产'",
 'NetProfit': "净利润'",
 'OperatingEvenue': "营业收入'",
 'OperatingCost': "营业成本'",
 'OperationProfit': "营业利润'"}

In [177]:


# 过滤 没有包含2015 2016 2017 这三年数据的公司
idWithYear={}
for d in x:
    _id,year = d['Symbol'],d['EndDate'][0:4]
    if '证券代码' in _id:
        continue
    if _id not in idWithYear:
        idWithYear[_id]=[]
    if year in ['2016','2017','2015']:
        idWithYear[_id].append(year)
deletedList = []
for (k,v) in  idWithYear.items(): 
    if len(v)<3:
        deletedList.append(k)
print('总公司数',len(set(df["Symbol"])),len(df["Symbol"]))      
print('没有包含2015 2016 2017 这三年数据的公司的公司数',len(deletedList)) 
display(df.head())
df_haslast3year = df[~df["Symbol"].isin(deletedList)]  
# print(df.shape)
# print(df2.shape)
# # 还剩下 3513记录
print('剩余公司数',len(set(df_haslast3year["Symbol"])),len(df_haslast3year["Symbol"])) 
df_haslast3year.head()

总公司数 3598 32194
没有包含2015 2016 2017 这三年数据的公司的公司数 759

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期',上市交易所',公司中文全称',行业名称',公司注册地址',省份',城市',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250
2,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585
3,000001,2005-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,229216415808,224173373853,41580457,351727460,NaN,NaN,674754526
4,000001,2006-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,260576263238,254101799991,26567410,1302906538,NaN,NaN,1905168852

剩余公司数 2839 30750

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit
0,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期',上市交易所',公司中文全称',行业名称',公司注册地址',省份',城市',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润'
1,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250
2,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585
3,000001,2005-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,229216415808,224173373853,41580457,351727460,NaN,NaN,674754526
4,000001,2006-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,260576263238,254101799991,26567410,1302906538,NaN,NaN,1905168852

In [178]:
# 过滤 10年中名称中包含ST的
import functools 
idMap = {}
for a in df_haslast3year.to_dict('records'):
    id = a['Symbol']
    if id not in idMap:
        idMap[id] = [];
    idMap[id].append(a['ShortName'])
reversedId = []
for (k,v) in  idMap.items(): 
    stNum = functools.reduce(lambda x,y: (1+x) if isinstance(y,str) and 'ST' in y  else  (0 + x) , v, 0)
    if stNum <10:
        reversedId.append(k)
        

df3 = df_haslast3year[df_haslast3year["Symbol"].isin(reversedId)]  
print('过滤 10年中名称中包含ST的，剩余公司数',len(set(df3["Symbol"])),len(df3["Symbol"])) 
df=df3

过滤 10年中名称中包含ST的，剩余公司数 2822 30495

In [179]:
"""
把ROA和托宾Q合并进来
"""
df6_ = load('./ROA数据来源0408.xlsx')
df6 = df6_.rename(columns={'Stkcd':'Symbol','Accper':'EndDate'})
df6 = df6.drop([1]) #删除第2行  没有单位'的哪一行
df6 = df6.drop_duplicates(["Symbol","EndDate"])
print('after drop_duplicates,shape=',df6.shape)
df6.loc[0]['Symbol']="证券代码'"
df6.loc[0]['EndDate']="统计截止日期'"
df6 = df6[['Symbol','EndDate', 'F050201B', 'F050202B','F050203B','F050204C']]
df6.head(3)

./ROA数据来源0408.xlsx (276588, 10)

,Stkcd,Accper,F050201B,F050202B,F050203B,F050204C,F050301B,F050302B,F050303B,F050304C
0,股票代码',截止日期',总资产净利润率（ROA）A',总资产净利润率（ROA）B',总资产净利润率（ROA）C',总资产净利润率（ROA）TTM',流动资产净利润率A',流动资产净利润率B',流动资产净利润率C',流动资产净利润率TTM'
1,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位'
2,000001,2018-12-31,0.00726,0.007445,0.007445,0.007445,NaN,NaN,NaN,NaN

after drop_duplicates,shape= (146208, 10)

,Symbol,EndDate,F050201B,F050202B,F050203B,F050204C
0,证券代码',统计截止日期',总资产净利润率（ROA）A',总资产净利润率（ROA）B',总资产净利润率（ROA）C',总资产净利润率（ROA）TTM'
2,000001,2018-12-31,0.00726,0.007445,0.007445,0.007445
3,000001,2018-09-30,0.006103,0.006198,0.006198,0.007548

In [180]:
df7_ = load('./托宾Q值来源0408.xlsx')
df7 = df7_.rename(columns={'Stkcd':'Symbol','Accper':'EndDate'})
df7 = df7[['Symbol','EndDate', 'F100501A', 'F100801A','F100802A','F100901A','F100902A','F100903A','F100904A','备注']]
df7.loc[0]['Symbol']="证券代码'"
df7.loc[0]['EndDate']="统计截止日期'"
df7 = df7.drop([1]) #删除第2行  没有单位'的哪一行
df7.head(3)

./托宾Q值来源0408.xlsx (137200, 11)

,Stkcd,Accper,Indcd,F100501A,F100801A,F100802A,F100901A,F100902A,F100903A,F100904A,备注
0,股票代码',截止日期',行业代码',市值有形资产比',市值A',市值B',托宾Q值A',托宾Q值B',托宾Q值C',托宾Q值D',只取12月年终的数据
1,没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',没有单位',NaN
2,000001,2018-12-31,J66,0.047282,3.33961e+12,3.33961e+12,0.047113,0.047283,0.976896,0.980435,NaN

,Symbol,EndDate,F100501A,F100801A,F100802A,F100901A,F100902A,F100903A,F100904A,备注
0,证券代码',统计截止日期',市值有形资产比',市值A',市值B',托宾Q值A',托宾Q值B',托宾Q值C',托宾Q值D',只取12月年终的数据
2,000001,2018-12-31,0.047282,3.33961e+12,3.33961e+12,0.047113,0.047283,0.976896,0.980435,NaN
3,000001,2018-09-30,0.056809,3.30656e+12,3.30656e+12,0.056602,0.05681,0.986427,0.990057,NaN

In [181]:
df = df.merge(df6,how='left',on=['Symbol','EndDate']).merge(df7,how='left',on=['Symbol','EndDate'])
print(df.shape)
df.head(3)

(30495, 68)

,Symbol,EndDate,ShortName,IndustryName,IndustryCode,RegisterAddress,Zipcode,EstablishDate,Listexg,Conme,Nindnme,Regadd,Province,City,Primed,Prisg,Pridt,Ucsnm,Ucsp,Ucscm,Ucpd,Ucsvr,Ucscr,Nshld,Empnum,Retnum,Bdnum,Dbdbum,Mtnum,Preshrt,Hdirrt,Prestw3,Vmntw3,A002100000,A001000000,B001100000,B002000000,T40801,Ucsbg,Chmap,Nshrttl,Nshrstt,Nshremp,Nshrsms,RDPerson,RDPersonRatio,RDSpendSum,RDSpendSumRatio,Explanation,TotalAssets,TotalLiability,IntangibleAsset,NetProfit,OperatingEvenue,OperatingCost,OperationProfit,F050201B,F050202B,F050203B,F050204C,F100501A,F100801A,F100802A,F100901A,F100902A,F100903A,F100904A,备注
0,证券代码',统计截止日期',股票简称',行业名称',行业代码',注册具体地址',办公地址邮政编码',公司成立日期',上市交易所',公司中文全称',行业名称',公司注册地址',省份',城市',民营化方式',民营化标志',转化日期',实际控制人名称',实际控制人类型',实际控制人控制上市公司方式',实际控制人是否担任董事长或总经理',实际控制人拥有上市公司控制权比例(%)',实际控制人拥有上市公司所有权比例(%)',股东总数',员工人数',离退休职工人数',董事会人数',其中：独董人数',监事会人数',董事长持股比例(%)',总经理持股比例(%)',董事前三名薪酬总额',高管前三名薪酬总额',流动负债',总资产',营业收入',净利润',净资产收益率(%)',实际控制人背景',控制链图',股本总数',其中：国有股',其中：内部职工股',其中：高管持股数',研发人员数量',研发人员数量占比(%)',研发投入金额',研发投入占营业收入比例(%)',说明',总资产',总负债',无形资产',净利润',营业收入',营业成本',营业利润',总资产净利润率（ROA）A',总资产净利润率（ROA）B',总资产净利润率（ROA）C',总资产净利润率（ROA）TTM',市值有形资产比',市值A',市值B',托宾Q值A',托宾Q值B',托宾Q值C',托宾Q值D',只取12月年终的数据
1,000001,2003-12-31,深发展A,货币金融服务,J66,深圳市罗湖区深南东路5047号,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,125390017,0,0,NaN,NaN,NaN,NaN,NaN,192851003723,188885919630,87090889,316545704,NaN,NaN,368537250,0.001641,0.001763,0.001763,0.001763,0.085903,2.01973e+11,2.05445e+11,0.085864,0.085903,1.0653,1.06578,NaN
2,000001,2004-12-31,深发展A,货币金融服务,J66,中国广东省深圳市,518001,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945822149,1717146,0,0,NaN,NaN,NaN,NaN,NaN,204286424020,199601761732,65857066,289774275,NaN,NaN,498516585,0.001418,0.001457,0.001459,0.001459,0.06279,2.10181e+11,2.12425e+11,0.06277,0.06279,1.03984,1.04017,NaN

In [182]:
from datetime import datetime
today = datetime.now().strftime("%m%d")

df.to_excel(f'./研究数据{today}_out.xlsx')